# Numpy Hello World

* numpy offers optimized data structures
* a large part of machine learning consists of massaging data into the format you need

In [1]:
# np is the common name
import numpy as np

In [2]:
# create an array

array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
type(array)

numpy.ndarray

In [4]:
# you can always ask for the shape of an numpy arrary

array.shape

(4, 3)

In [5]:
# accessing a single element

array[0, 0]

1

In [6]:
# accessing a single row

array[0]

array([1, 2, 3])

In [7]:
# accessing a single column

array[:, 0]

array([ 1,  4,  7, 10])

In [8]:
# accessing a range

array[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [9]:
# transpostion

array.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [10]:
# give it a new shape

array.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [15]:
# flatten

array.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
# max of all elements

array.max()

12

In [29]:
array

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
# max for each row

array.max(axis=1)

array([ 3,  6,  9, 12])

In [22]:
# max for each column

array.max(axis=0)

array([10, 11, 12])

In [24]:
# index for max element

array.argmax()

11

In [26]:
array.argmax(axis=1)

array([2, 2, 2, 2], dtype=int64)

In [27]:
array.argmax(axis=0)

array([3, 3, 3], dtype=int64)

In [12]:
# convenience function to create arrays

np.linspace(1, 1, 6)

array([1., 1., 1., 1., 1., 1.])

In [13]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
np.arange(1, 6, 1)

array([1, 2, 3, 4, 5])

## Exercise

1. execute this notebook
    * you can execute each cell by hitting shift+enter
1. create your own array and transform it in random ways
    * you will need some of the documentation which you get by putting a questionmark after the API Call
    * e.g.: np.arrange?